all: zui_win_test.cpp
	arm-linux-g++ -c -o zui_win_test.o zui_win_test.cpp \
		-I ../../include/soc -I ../../zbwos_core -I ../../file_system -I ../../user/jpeg -I ./zui -I ../../user/zjpeg
clean:
	rm zui_win_test.o -rf

